### ISSUE TITLE
Webkit not loading image untill you scroll a little bit

### ISSUE THREAD

**Issue by 10257** [tuupola/jquery_lazyload#138]
On a big screen (image 27") after a reload, image are not loaded if you don't scroll a little.
Exemple on page : http://max.jynk.fr/web/carrefour/
I found a workarround, but it only work in firefox (see code below).

``` Javascript
var $imgs = $(".slides .pix img.lazy");
$imgs.lazyload({
    failure_limit : Math.max($imgs.length - 1, 0)
});
$window.trigger("scroll");
```

**Comment by Ignitis** [comment]
how can i set skip_invisible to false? I mean modify which file and where?

**Comment by kr0hmy** [comment]
There is an example using this parameter on the project page :) http://www.appelsiini.net/projects/lazyload#dealing-with-invisible-images
Just set it to false instead!
