### ISSUE TITLE
Conflict with scriptaculous effects.js

### ISSUE THREAD

**Issue by mage-eag** [tuupola/jquery_lazyload#139]
Using `$this.trigger("appear");` conflicts with `Effect.Appear` from `scriptaculous`, and makes images flicker

**Comment by TomFranssen** [comment]
All current releases of Magento 1.x make use of this ancient PrototypeJS library.
I suggest to change the name of the event to make the plugin work even when ProtoypeJS is loaded:
http://stackoverflow.com/a/19054432/1627848
