### ISSUE TITLE
Publish / Update NPM registry with latest version

### ISSUE THREAD

**Issue by arboleya** [tuupola/jquery_lazyload#159]
It'd be nice to have this package on NPM.

I found this one, but it's on version 1.8.4.
https://npmjs.org/package/lazyload

Tks

**Comment by tapsboy** [comment]
I see this now https://www.npmjs.com/package/jquery_lazyload

**Comment by tuupola** [comment]
Official is this: https://www.npmjs.com/package/jquery-lazyload

**Comment by tapsboy** [comment]
:ok_hand:
