### ISSUE TITLE
Force reload

### ISSUE THREAD

**Issue by yamila-fraiman** [tuupola/jquery_lazyload#215]
Hi, I want to update a profile picture so when the server returns I want to force refresh.
I tried setting an event in the options and then trigger it but it didnt work for me.

Regards.

**Comment by estebandinamarca** [comment]
I am also using Angular.js. I would like to use ```ng-src``` in each image.
Where can I change "data-original" attribute?  

Replace this:
```
<img class="lazy" data-original="{{user.photo}}">
```
For this:
```
<img class="lazy" ng-src="{{user.photo}}">
```
