### ISSUE TITLE
Hidden image doesn't load

### ISSUE THREAD

**Issue by kumold** [tuupola/jquery_lazyload#231]
http://jsbin.com/qawixe/1/edit?html,css,js

Image loads after showing and scrolling a bit.

**Comment by dejurin** [comment]
<img width="411" alt="2018-08-13 16 39 29" src="https://user-images.githubusercontent.com/4470015/44035164-7d0bcbe2-9f17-11e8-9a54-af3fa513bf71.png">
I have situation when I scroll down before show my hide image.
