### ISSUE TITLE
Plugin make slow down page

### ISSUE THREAD

**Issue by kreker92** [tuupola/jquery_lazyload#235]
I have manu imgs on my page. about 1 thousand. Its really slow down.
I've tried to use this decision but it doesnt work for me.

http://stackoverflow.com/questions/17428976/jquery-lazyload-plugin-slowing-down-div-scrolling/17431675#17431675

The problem is in staying searching scrolling element if he had already loaded

**Comment by montrothstein** [comment]
Victor,

As Mika said you will want to use the scrollstop event.  However for my use
case that wasn't enough.  I needed it to work with 5000+ images.  I forked
lazyload and my fork makes several performance improvements.  There are
some (minor to me but YMMV) breaking changes, all commented in the code.

https://github.com/montrothstein/jquery_lazyload

-Mont
