### ISSUE TITLE
failure_limit ??

### ISSUE THREAD

**Issue by paper** [tuupola/jquery_lazyload#237]
Hi~

code(Version:  1.9.3):
https://github.com/tuupola/jquery_lazyload/blob/master/jquery.lazyload.js#L53
https://github.com/tuupola/jquery_lazyload/commit/985be23e24a198b2a3048639eb9c9ace6b5f77ed

[Demo]
faile       :  https://paper.github.io/lab/lazyload-test/faile/lazyload-test.html
success : https://paper.github.io/lab/lazyload-test/success/lazyload-test.html
  
[English]
my english is not good , I try my best to express my meaning

because  failure_limit = 0
so, if one image  below the fold , then ``` return false; ```, break the ```each```.
but, other images possible appear in fold and should ```trigger("appear");```
Although I can set ```failure_limit``` , but it is hard. 
because the page height often change or every page have different needs

---

[Chinese]
默认 failure_limit 为 0
也就是说，当elements循环时，一发现有图片在可视区域下面（假设其中一个叫A），++counter 大于 0，return false; each 循环停止 。
这会导致有些图片虽然在可视区域，但DOM节点处在A下面，就不会加载了。

虽然可以设置 failure_limit 的数量，但是每个页面的需求不同，而且页面的高度可以随时变化，这个值是很难设置，所以意义不大
                        
希望 去掉这个属性，或者 return true; 或 do Nothing.

**Comment by tuupola** [comment]
Bind plugin separately to left and right columns. Something like:

```
$("#left img").lazyload(...);
$("#right img").lazyload(...);
```

**Comment by paper** [comment]
thank you~  that's right.  but I really only want to use:
```
$("img.lazy").lazyload(...);
```

could you set a “Switch" like this :  
```
$("img.lazy").lazyload({
  close_failure_limit  : true
});
```

Because,  not only left and right columns, columns is uncertain. 
If I have many different pages, that coupling too high. 
I only care about the images. thank you.

**Comment by tuupola** [comment]
If you do not want to use the proper solution as suggested then as a workaround use huge failure_limit number.

```
$("img.lazy").lazyload({
    failure_limit  :  99999999999
});
```

**Comment by paper** [comment]
oops~
