### ISSUE TITLE
Empty data:image loaded instead of correct image

### ISSUE THREAD

**Issue by simonferndriger** [tuupola/jquery_lazyload#239]
Lazyload works perfect for most of the images on our site, but since we tried to load some additional images with lazyload, instead of the real image, an empty/gray `data:image` gets loaded instead. The end result looks like this:

`<img class="foto lazy" data-original="http://images.topin.travel/medium//d7/42148527df98f6e5d7.jpg" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC">`

**Comment by simonferndriger** [comment]
The images on the website are in viewport by default (but not allways). When I completely scroll down the whole page, and up again, the images are loaded correctly...

Can you help me out here?

**Comment by tuupola** [comment]
URL of the page you have problem with? Do you have problem with [different](http://www.appelsiini.net/projects/lazyload/enabled_fadein.html) example [pages](http://www.appelsiini.net/projects/lazyload/enabled_gazillion.html)?

**Comment by simonferndriger** [comment]
Hi Mike

This is an example URL which does not work:
http://dev.swisswebcams.ch/webcam/1292514156-Aletsch-Arena-Riederalp-Aletschgletscher-%283987-Riederalp%29_Wetter
(Please keep it confidential, since it is only for developing purposes)



Best
Simon

www.lookr.com <http://www.lookr.com> — Take a look around the world

Am 15.01.2015 um 12:52 schrieb Mika Tuupola:

**Comment by tuupola** [comment]
On Jan 15, 2015, at 7:37 PM, simonferndriger <notifications@github.com> wrote:

> Hi Mike
> 
> This is an example URL which does not work:
> http://dev.swisswebcams.ch/webcam/1292514156-Aletsch-Arena-Riederalp-Aletschgletscher-%283987-Riederalp%29_Wetter
> (Please keep it confidential, since it is only for developing purposes)


If you mean the right column (div.teaser) then read "When images are not sequential" in documentation or alternatively bind the plugin separately to those two columns.

$("div.teaser img.lazy").lazyload(...);
$("div.left img.lazy").lazyload(...);

-- 
Mika Tuupola
http://www.appelsiini.net/

**Comment by simonferndriger** [comment]
Thank you. Your example did load the teaser, but not the other small images. But this one seems to work - not an ideal implementation/handling, but at least it does its job now:

			$("div.teaser img.lazy").lazyload({ threshold : 100, effect : "fadeIn" });
			$("a.thumbnail img.lazy").lazyload({ threshold : 100, effect : "fadeIn" }); 

Thank you for your fast response, Mike!

**Comment by simonferndriger** [comment]
Can you please delete the example URL - since this URL should be confidential, thank you.
