### ISSUE TITLE
Images not loaded initially - Fix proposal

### ISSUE THREAD

**Issue by daverupp** [tuupola/jquery_lazyload#241]
Hey all
When I load images the first time, they are not loaded via the lazyload plugin. Only when I scroll a little bit, then it is working without problems.

I checked the plugin and changed this line in the update method:

if (settings.skip_invisible && $this.css('display') === 'none') {
//if (settings.skip_invisible && !$this.is(":visible")) {

It seems, that it is a problem with jquery's .is(':visible') method. So after the small change, it is working properly.

I hope this helps.
Kind regards
Dave

**Comment by tuupola** [comment]
You are using Safari and images do not have width and height attributes set? For jQuery they are invisible images. So you could also set `skip_invisible` to `false` or add width and height to images.

**Comment by daverupp** [comment]
No I am not using Safari... It is on all browsers not working. I set the width and height to the DIV and include the IMG with width 100% & height 100% in it.

Well it is working with the above change, I just wanted to post my experience in case any one other is struggling with such an issue.

**Comment by karussell** [comment]
Having the same problem with Firefox and Chromium. When explicitly setting weight & height to a fixed 'px' value I get empty gray rectangles, only when doing a minor scrolling this is okay.

> So you could also set skip_invisible to false

Are images not in viewport still lazy loaded then?

**Comment by karussell** [comment]
The fix from @daverupp seems to work

**Comment by tuupola** [comment]
Or you can just use `skip_invisible` to false. No it will not load all images. It will just also check if images which are not `:visible` appeared in viewport.

**Comment by tuupola** [comment]
Since 1.9.5 `skip_invisible`now defaults to `false`. Too much confusion about what it does.
