### ISSUE TITLE
LazyLoad and NiceScroll

### ISSUE THREAD

**Issue by joshgarth22** [tuupola/jquery_lazyload#245]
Hello!

Beautiful plugin, first off; it works flawlessly when bound to a regular element and does precisely what I'm looking for.  That said, I've implemented a div with the jquery NiceScroll plugin and all of a sudden, lazy load doesn't work on said div.  It'll scroll, but it doesn't fire lazyload when I reach the bottom of the screen.  Not sure what the issue is.

Any ideas?

**Comment by tuupola** [comment]
Your scroll plugin most likely does not fire scroll event in the div.
