### ISSUE TITLE
Callback after "each" image is loaded

### ISSUE THREAD

**Issue by greaveselliott** [tuupola/jquery_lazyload#246]
Would be great to be able to pass an callback after "each" image is loaded

**Comment by tuupola** [comment]
You can use `load`event for that. There is also `appear` event which is called when image appears on view but is not loaded yet.

```javascript
$("img.lazy").lazyload({
    appear : function(elements_left, settings) {
        console.log(this, elements_left, settings);
    },
    load : function(elements_left, settings) {
        console.log(this, elements_left, settings);
    }
});
```

**Comment by oninross** [comment]
This should be in the doco :P  really helpful.
