### ISSUE TITLE
Dynamically created images - Unbind before binding

### ISSUE THREAD

**Issue by jaredreich** [tuupola/jquery_lazyload#259]
First of all, excellent plugin, great work.

In the case of dynamically created images being used with lazyload, in order to avoid slowdown and lazyload getting binded more than once:

In jquery.lazyload.js, lines 79-83 should be changed to:

``` javascript
if (0 === settings.event.indexOf("scroll")) {
    $container.unbind('.lazyload');
    $container.bind(settings.event+'.lazyload', function(event) {
        return update();
    });
}
```

Sorry, I do have GitHub but am still major noob and am not comfortable making pull requests to such a popular repo.

Thanks for implementing this if you agree with it.

Jared

**Comment by zowers** [comment]
` $window.bind("resize"` is even bigger problem cause it adds resize handler each time you call $el.lazyload()

**Comment by tuupola** [comment]
This should be fixed now.
