### ISSUE TITLE
emit event when lazyload image substitution occurs

### ISSUE THREAD

**Issue by macgyver** [tuupola/jquery_lazyload#261]
Sometimes it helps to know when a placeholder image has been swapped out, but since the plugin is designed to augment existing image tags in the document I don't think there's a "load" event that we can generically bind to which will provide this information - have you ever considered triggering a custom event on the `<img>` tag after the effect has been animated, e.g.
```js
$self[settings.effect](settings.effect_speed, function(){
    $self.trigger('lazyload.loaded');
});
```

**Comment by tuupola** [comment]
There is `appear` and `load` events which you could use.

```javascipt
$("img.lazy").lazyload({
    appear : function(elements_left, settings) {
        console.log(this, elements_left, settings);
    },
    load : function(elements_left, settings) {
        console.log(this, elements_left, settings);
    }
});
```

More info at http://www.appelsiini.net/2012/lazyload-170

**Comment by macgyver** [comment]
Oh great, thanks! I didn't see that on the main project page. Is there documentation with all the options and events listed by version, or do I just need to read all the changelogs in order?

**Comment by macgyver** [comment]
Another related question - since the effect to fade the image in can have a duration, have you thought about an additional option, like "after_load"?
