### ISSUE TITLE
Wrong package name in bower.json

### ISSUE THREAD

**Issue by corysimmons** [tuupola/jquery_lazyload#264]
You have `jquery_lazyload`. It should be `jquery.lazyload`.

I think.

**Comment by tuupola** [comment]
Fixed. I have no idea why it was wrong. Thanks!

**Comment by corysimmons** [comment]
:+1:

**Comment by diggy** [comment]
@tuupola maybe fix this in the master branch as well? When people quickly consult your github repo to get the bower package name they end up with spencermefford's fork. Last release in that fork is `1.9.1`. Might be an idea to ping spencermefford and ask him to deregister `jquery_lazyload ` from the Bower registry.
