### ISSUE TITLE
placeholder issues with Content-Security-Policy header

### ISSUE THREAD

**Issue by jk3us** [tuupola/jquery_lazyload#265]
If you have a Content-Security-Policy that forbids `data:` urls (`default-src 'self'` or `img-src 'self'), this plugin causes an error:

Firefox:

```
Content Security Policy: The page's settings blocked the loading of a resource at data:image/png;base64,iVBORw0...
```

Chrome:

```
Refused to load the image 'data:image/png;base64,iVBORw0...' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.
```

In Firefox, **this seems to stop the execution altogether**, and the intended images don't load at all.  Chrome throws the error but then continues.

The "fix" is to pass a placeholder option into the lazyload() OR specify a src attribute on the image.... So the solution is probably to just mention this in the documentation.

**Comment by tuupola** [comment]
You can define external placeholder with something like:

```javascript
$("img.lazy").lazyload({ placeholder: "https//example.com/placeholder.png"});
```
