### ISSUE TITLE
Does not work in WordPress 4.2.4

### ISSUE THREAD

**Issue by IgorMyskiv** [tuupola/jquery_lazyload#276]
Thanks for the good plugin. It worked very well for WordPress 4.1.7. But when I updated WordPress 4.1.7 in the new version 4.2.4, pictures stopped loading. How to fix the problem in a WordPress 4.2.4?

**Comment by tuupola** [comment]
No idea. It is jQuery plugin and not realted to Wordpress in any way. You might be using some Wordpress implementation of it.

**Comment by IgorMyskiv** [comment]
I know this is jQuery plugin , and I added it to a WordPress template by your instruction.
And on WordPress 4.1.7 all works very well. Here is the link you can see: www.nebesnasotnya.com
But I can't update the WordPress in 4.2.4, because stops working Your plug-in. ((

**Comment by IgorMyskiv** [comment]
this instruction I used to embed the plugin in the site template - http://www.appelsiini.net/projects/lazyload/enabled_fadein.html

**Comment by tuupola** [comment]
Open console to see if there are any JavaScript errors when using  Wordpress 4.2.4. Also see if 4.2.4 generates different HTML than 4.1.7. Lazy Load plugin works on HTML so it is not tied to Wordpress itself in any way.

**Comment by IgorMyskiv** [comment]
Thanks for Your hint, I found a bug in the code. This is $. WordPress 4.1.7 of this error was not noticed and the plugin worked well, but the new WordPress 4.2.4 it has been considered a critical error.
It was enough to replace in the code the $ with jQuery and now Your plugin is working well again on the updated Wordpress !!! :-)

The correct code in the site template (for new WordPress 4.2.4) like this:
<script type="text/javascript" charset="utf-8">
  jQuery(function() {
     jQuery("img.lazy").lazyload({
        //failurelimit : 10,//
		threshold : 300,
		effect : "fadeIn"
     });
  });
  </script>

**Comment by IgorMyskiv** [comment]
The correct code in the site template (for new WordPress 4.2.4) like this: 
<script type="text/javascript" charset="utf-8">
  jQuery(function() {
     jQuery("img.lazy").lazyload({
        //failurelimit : 10,//
		threshold : 300,
		effect : "fadeIn"
     });
  });
  </script>

**Comment by IgorMyskiv** [comment]
Thank you. The problem is solved.

**Comment by tuupola** [comment]
Glad you found a solution!
