### ISSUE TITLE
Does lazyload.js affect indexability?

### ISSUE THREAD

**Issue by chickenorbeef** [tuupola/jquery_lazyload#277]
Currently the sitemaps I generate for SEO purposes only see my loader.gif. How can I get my images rendered through lazyload to get indexed by crawlers?

Thanks in advance.

**Comment by tuupola** [comment]
If crawler parses and executes JavaScript then it can see the original image. If not then crawler sees the loader image.

**Comment by chickenorbeef** [comment]
Gotcha. Currently I've just added <noscript> tags for rendering an image in case Google has issues with the js. Do you think that is a sufficient solution?

**Comment by tuupola** [comment]
Since I do not know what you actually did cannot tell for sure. But if you can see image tag by viewing the source then Google should see it too. I think Google has a tool for testing that too. In Webmaster Tools or something similar.
