### ISSUE TITLE
compiler errors out when using npm install --save jquery-lazyload

### ISSUE THREAD

**Issue by eschow** [tuupola/jquery_lazyload#281]
I used `npm install --save jquery-lazyload` to install the plugin and my gulp-watch compiler kept erroring out with the following message: 

    [Compile Error] Error: Parsing file /Users/chowes/Code/postgraphics/entertainment/2015-national-book-festival/src/js/base.js: Unexpected token (185:34)

It turns out that the package.json "main" property is pointing to "Gruntfile.js," which does not get installed with the existing set-up. I changed it to "jquery-lazyload" and it compile successfully.

Has anyone else run into this problem?

**Comment by tuupola** [comment]
Can you test if version 1.9.7 fixes the problem.

https://www.npmjs.com/package/jquery-lazyload

**Comment by eschow** [comment]
Yes, it does. Thanks.
