### ISSUE TITLE
Add custom "update" event or run "update" on init.

### ISSUE THREAD

**Issue by WebProgerLive** [tuupola/jquery_lazyload#282]
I load images via ajax and on success the plugin is inited. But events if images are above threshold, they are not loaded untill i scroll. I think, it would be a good idea to run update event on init.

**Comment by tuupola** [comment]
You can  do `$(window).trigger("scroll")` or something similar in ajax callback.

**Comment by WebProgerLive** [comment]
i did it. but it does not work. it only works when i set `$(window).trigger("scroll")` in timeout. but it is not the best way, i think. anyway, `$(window).trigger("scroll")` looks like a hack.
