### ISSUE TITLE
Dynamically image change

### ISSUE THREAD

**Issue by FrancisRoy** [tuupola/jquery_lazyload#286]
Hi

Our pages need to toggle between two images to display the products.
When using the lazy load plugin, it seems to get back to the original one, and even if I change the value of the data-orginal attributes.  Do I need to use the update method that I see in the script ?
If yes, what is the syntax to call the method.  I am assuming that use the container in the code to get the value.

Thx

**Comment by tuupola** [comment]
Cleaning up old issues.
