### ISSUE TITLE
Images not lazyloading unto scroll stops (webkit)

### ISSUE THREAD

**Issue by tommybstitch** [tuupola/jquery_lazyload#287]
I am having an issue with webkit browsers where my images will not lazyload until the user actually stops scrolling. 

While the user is scrolling past the images, they remain unloaded until the scroll event stops completely. Is there any known fix or workaround for this? Thanks. 

EDIT: I am not using a container, just the `$(window)`

Also: This is happening on an infinitely scrolling page that loads a grid of results, each with an image, 20 results at a time. The first 20 results seem to be loading fine (even while scrolling), it's once I scroll to the second page of results that this happens.

**Comment by tuupola** [comment]
If you mean mobile Safari et al. you are correct that is how their scroll even works. On desktop browsers? `onscroll` event is fired continuously while the user scrolls.  On most mobile browsers `onscroll` event is  fired when user stops scrolling. You could try using `ontouchmove` instead.

**Comment by tuupola** [comment]
This should be fixed in [2.x](https://github.com/tuupola/jquery_lazyload/tree/2.x).
