### ISSUE TITLE
jQuery.noConflict causes $(...).lazyload is not a function

### ISSUE THREAD

**Issue by EddieOne** [tuupola/jquery_lazyload#289]
I have had to use the noConflict option in jquery because the project I'm working on has loaded 2 versions of it. It's not ideal but for the moment, it's the only option.

I'm wondering if there is a way to workaround this problem. This is what I have.

After 2nd jquery is loaded. The one I use lazyload for

    var $j = jQuery.noConflict();

and later on in the script I tried this with no luck

    try{
        $j("img.cthumb").lazyload({
            container: $(".friendslist")
        });
    }catch(e){
        $("img.cthumb").lazyload({
            container: $(".friendslist")
        });
    }

**Comment by tuupola** [comment]
Never used two versions of jQuery in one page. But maybe it should be something like.

```javascript
$j("img.cthumb").lazyload({
    container: $j(".friendslist")
});
````

**Comment by EddieOne** [comment]
Thanks! I think that is it. I'm going to try and consolidate my jquerys though.
