### ISSUE TITLE
preloader image

### ISSUE THREAD

**Issue by kudataz** [tuupola/jquery_lazyload#296]
is possible to create preloader image before main img has loaded?
please script :dancer:

**Comment by tuupola** [comment]
You can use the placeholder or just put it into the `src` parameter.

```html
<img class="lazy" src="img/preloader.gif" data-original="img/example.jpg" width="640" height="480">
```

```javascript
$(function() {
    $("img.lazy").lazyload();
});
```

**Comment by kudataz** [comment]
case closed,
 i think before is edit in jquery to make preleader, but set in html tag hhii :D 
Thanks a lot @tuupola

**Comment by roydekleijn** [comment]
@tuupola like this your preloader becomes really big isn't it ?
