### ISSUE TITLE
Need way to load image manually

### ISSUE THREAD

**Issue by DmitryFillo** [tuupola/jquery_lazyload#298]
Now we can load image on scroll or on resize. I suggest to add event for manual image load, example: 

    $('.lazy-img').trigger('update');

What are use cases? I think that this feature will help to integrate this plugin with sliders and etc. Sliders doesn't fire 'resize' or 'scroll' events and should not to do it, but what if we want to load some images on slide?

Also this feature is easy to implement and will not break any things, but gives to the developer the choice when to load image.

Any thoughs, why it's good or bad? If it's not bad, I will make pull request.

**Comment by tuupola** [comment]
You can do that already. See for example:

http://www.appelsiini.net/projects/lazyload/enabled_timeout.html

Above page uses custom event called `sporty`, usually you just use `scroll` or something similar.

**Comment by DmitryFillo** [comment]
Sorry, i was inconsiderate, good implementation :)
