### ISSUE TITLE
Images not showing up in other pages with datatable

### ISSUE THREAD

**Issue by opnchaudhary** [tuupola/jquery_lazyload#299]
Hello, I am trying to use this plugin with DataTables (http://datatables.net/). The images load in the first page in a paginated table but when I move to other pages of the paginated table, the image doesn't show up. 
Thanks

**Comment by jangrewe** [comment]
I'm using this plugin with DataTables, too - successfully! 
You probably need to call the lazyload() function again after getting new data into the table, because those images haven't been "lazyfied" yet.
