### ISSUE TITLE
bug in lazy's selectors as i think

### ISSUE THREAD

**Issue by Perlover** [tuupola/jquery_lazyload#302]
Hi,

After researching code i think i found bug
There is fix and few optimization of code

https://github.com/tuupola/jquery_lazyload/compare/master...Perlover:patch-1

**Comment by Perlover** [comment]
There in selectors used the code where used the settings.container
But in your code settings.container will be undefined everytime even if user uses settings.container settings ;-)

**Comment by tuupola** [comment]
Patches to open source projects should follow the coding style of the original project. For example curly braces should be used in if sentences etc.

Also I do not really understand the problem this fixes. Can you show some example code which demonstrates the problem.

**Comment by Perlover** [comment]
I cannot demonstrate ;-)
But i see in code that is strange to use selector's code and don't pass to it other settings but only threshold. Can you see in code yourself?

**Comment by tuupola** [comment]
Plugin itself does not use `:below-the-fold` style selector. They are just included there as utility if somebody wants to do something like `$("img:below-the-fold").something()`.

**Comment by Perlover** [comment]
These lines will not be executed for selectors without patch if user uses lazyload({container:...})

https://github.com/tuupola/jquery_lazyload/blob/master/jquery.lazyload.js#L215
https://github.com/tuupola/jquery_lazyload/blob/master/jquery.lazyload.js#L203
https://github.com/tuupola/jquery_lazyload/blob/master/jquery.lazyload.js#L191
https://github.com/tuupola/jquery_lazyload/blob/master/jquery.lazyload.js#L179

So selectors will not work for container's way

**Comment by Perlover** [comment]
> if somebody wants to do something like $("img:below-the-fold").something(). 
Yes, but this "somebody" will not get a right results if he uses container option

**Comment by Perlover** [comment]
I think this example will not work with user's using of selectors
http://www.appelsiini.net/projects/lazyload/enabled_container.html
