### ISSUE TITLE
There are many "bind" events but no "unbind"

### ISSUE THREAD

**Issue by hollton** [tuupola/jquery_lazyload#304]
```
    Such as:
    /* Check if something appears when window is resized. */
    $window.bind("resize", function() {
        update();
    });
```

**Comment by Amaza-na** [comment]
ok

**Comment by coffy** [comment]
is there a way to unbind lazyload properly? It looks like it can generate scrolling performance issues when called multiple times

**Comment by UCIS** [comment]
Also not unbinding from the resize event will cause a memory leak if the lazyload container is removed from the DOM.

**Comment by tuupola** [comment]
This should be fixed in [2.x](https://github.com/tuupola/jquery_lazyload/tree/2.x).
