### ISSUE TITLE
Are Lazy Loaded Images Crawled By Google?

### ISSUE THREAD

**Issue by ModDM** [tuupola/jquery_lazyload#306]
Regarding the widely found issue on the web about dynamically loaded content that is / was not crawled by Google, my question is if Lazyload images are available for Google to crawl it and to show it for example on Google Images site (images.google.com).

**Comment by tuupola** [comment]
Doing an [site:www.appelsiini.net](https://www.google.com/search?site=&tbm=isch&source=hp&biw=1198&bih=750&q=site%3Awww.appelsiini.net) search seems to reveal several car images which are from lazyload demo pages.

**Comment by ModDM** [comment]
A practicle example = the best answer! Thank you very much.

**Comment by ModDM** [comment]
It's okay, because it works correctly, but I was just wondering about some little thing that might explain it: 
Google recognizes it, maybe by reading Javascript, but maybe because of the src attribute. This attribute is not in the original HTML, but am I right that this attribute is dynamically added to the img tags by the script?

**Comment by ModDM** [comment]
Thank you Peter. Always good to know how Google works, since we can not without Google nowadays.

**Comment by ankur0890** [comment]
@tuupola hey i checked. Images that are getting crawled are not from the lazyload page. They are from http://www.appelsiini.net/projects/viewport/3x2.html in which images are not lazy load. My sie is using this plugin and my images are not getting cralwed by google

**Comment by ModDM** [comment]
Hey, you are right @ankur0890. Has something changed @tuupola?

**Comment by vin-sha** [comment]
Lazy loaded images are being crawled by Google,

Google it "jquery smartify" for images and see the result

**Comment by tuupola** [comment]
I can see images which are from lazyload demo pages.
