### ISSUE TITLE
Single quotes in image URL is not working

### ISSUE THREAD

**Issue by shashank-saxena** [tuupola/jquery_lazyload#308]
I am using this image as css background `https://images.activityhero.com/activity_photo/4859/large/It's_yoga_kids_group.jpg`, But when i passed it to the data attribute as escaped URL like this `https://images.activityhero.com/activity_photo/4859/large/It\'s_yoga_kids_group.jpg`.

It hits the encoded version of URL `https://images.activityhero.com/activity_photo/4859/large/It%5C's_yoga_kids_group.jpg"`, in the dummy image tag and thus it fails to load and it results in no image in background.

**Comment by tuupola** [comment]
You are kind of asking trouble by using special characters in URL. It would be better just to use URL safe characters.
