### ISSUE TITLE
Is possible to modify this plugin to support lazy load iframe?

### ISSUE THREAD

**Issue by SLyHuy** [tuupola/jquery_lazyload#309]
Hi, as title, is possible to modify this plugin to support lazy load iframe? if possible I'll fork and contribute this plugin.
Thank you.

**Comment by casbboy** [comment]
I was wondering the same thing. Need iFrame lazy load.

**Comment by SLyHuy** [comment]
You can check my fork. I added it already :)

On Tuesday, 15 March 2016, casbboy <notifications@github.com> wrote:

> I was wondering the same thing. Need iFrame lazy load.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tuupola/jquery_lazyload/issues/309#issuecomment-196552319>
> .
>


-- 

Huy Lý

**Comment by casbboy** [comment]
Thanks! Found it. :)

**Comment by casbboy** [comment]
Can the script pick up an iframe that was created on document ready? 

Cheers!
Ryan

**Comment by vinaykrsharma** [comment]
@SLyHuy You can use this https://github.com/vinaykrsharma/jquery.smartify

This plugin has capability to lazify any type of elements.

**Comment by tuupola** [comment]
This plugin is for images only.
