### ISSUE TITLE
Default Image if Original Image Error

### ISSUE THREAD

**Issue by akhilrajau** [tuupola/jquery_lazyload#312]
I am using this lazy loading and having some issue. Lazy load having place holder image which shows before loading the original image which is nice. 

But i need to set a different image when the original image is error. Now i got like onError event is not handled. So the src attribute is not replaced with original one even i use appear section to replace with src. 

I found like i can include onError method to handle this with a separate setting key. I think think this is useful. 

Can i include this functionality in my source js

**Comment by Jevirs** [comment]
OK,I got it.
1. open this JS file https://github.com/tuupola/jquery_lazyload/blob/master/jquery.lazyload.js
2. find line 129, add this .on("error", $self.attr("src","images/error.png})
3. And it looks like 
 .attr("src", $self.attr("data-" + settings.data_attribute)) 
 .on("error", function() { $self.attr("src","images/error.png"); }) 
4.minify the JS file and enjoy

**Comment by akhilrajau** [comment]
OK thanks

**Comment by xiaohaoo** [comment]
为什么把原生的onerror给屏蔽掉？
