### ISSUE TITLE
Do not work in safari

### ISSUE THREAD

**Issue by shaman900** [tuupola/jquery_lazyload#313]
Please look this site in safari http://dendra/catalog/arbalety_dlya_okhoty/

**Comment by tuupola** [comment]
http://dendra/catalog/arbalety_dlya_okhoty/ is not a valid url.

**Comment by shaman900** [comment]
Sorry this http://dendra.ru/catalog/arbalety_dlya_okhoty/
After load page in safari, img have src = placeholder, why?

**Comment by tuupola** [comment]
Honestly no idea. Images appear as they are supposed to. Then there seems to be some event in the end of page loading which removes the images. I would debug by disabling other JavaScript plugins one by one to see if there is a conflict. Another way is to try to compare what is different with the [demo page](http://www.appelsiini.net/projects/lazyload/enabled.html).

**Comment by shaman900** [comment]
Ok, thank you very much, I will seek
