### ISSUE TITLE
no jquery

### ISSUE THREAD

**Issue by infeng** [tuupola/jquery_lazyload#314]
my website is not use jquery,i hope lazyload can make a no-jquery version

**Comment by verlok** [comment]
Check out this https://github.com/verlok/lazyload
It's a no jQuery version of this jQuery lazyload, much faster, to which you can migrate easily. 
We use it in production in the category pages of many of our ecommerce websites.
Let me know!

**Comment by infeng** [comment]
@verlok thanks,i will try!

**Comment by tuupola** [comment]
[2.x](https://github.com/tuupola/jquery_lazyload/tree/2.x) works without jQuery.
