### ISSUE TITLE
about TAB issue

### ISSUE THREAD

**Issue by codesboy** [tuupola/jquery_lazyload#317]
If jquery_lazyload.js meet TAB ,It'll can't work unless we rolling screen

**Comment by AxelBriche** [comment]
Same problem.

**Comment by tuupola** [comment]
What is TAB?

**Comment by AxelBriche** [comment]
@tuupola example: https://puu.sh/ubOCp/d350792a98.png
Buttons, and when we click on a button, the content change.

**Comment by AxelBriche** [comment]
Fixed with event trigger.

**Comment by codesboy** [comment]
@AxelBriche Great！！

**Comment by mitkovalkov** [comment]
@AxelBriche I have the same problem, can you put a jsfiddle or something to see how you fixed the issue, 10x

**Comment by tuupola** [comment]
Can you try [2.x](https://github.com/tuupola/jquery_lazyload/tree/2.x) which is still work in progress though.
