### ISSUE TITLE
LazyLoad image with set sameheight for wrap of image.

### ISSUE THREAD

**Issue by chinhphan099** [tuupola/jquery_lazyload#318]
Hi,

I have problem how to set sameheight for the wrapper tags of images on one row.
I need a method after image showed to call my function and then get height of image.
Please add callback afterShow for lazyload in this plugin.

Thanks :)

**Comment by tuupola** [comment]
You could use the `appear` and `load` callbacks. First one is called when image enters the viewport. Second is called when the image has been loaded.

```
    $("img.lazy").lazyload({
        appear : function(elements_left, settings) {
            console.log(this, elements_left, settings);
        },
        load : function(elements_left, settings) {
            console.log(this, elements_left, settings);
        }
    });
```
