### ISSUE TITLE
can i work in the mobile web?

### ISSUE THREAD

**Issue by semi-xi** [tuupola/jquery_lazyload#319]
in mobile web ,i use zepto but not the jquery,so it can't work and throw "Cannot set property 'below-the-fold' of undefined" 
how can i do to kepp it work.
you konw zepto and jquery  are similar。i don't like load all of them

**Comment by verlok** [comment]
Check out this https://github.com/verlok/lazyload
It's a lazy load script much faster than jQuery LazyLoad, to which you can migrate easily, and which support the srcset attribute so retina images are fully supported.
We use it in production in the category pages of many of our ecommerce websites.
Let me know!

**Comment by verlok** [comment]
Sorry I forgot to say that it's a version of this plugin but without jQuery dependence. So you can use it in mobile (also because it's faster) or wherever you want.

**Comment by semi-xi** [comment]
thank u very much~

**Comment by tuupola** [comment]
This should be fixed in [2.x](https://github.com/tuupola/jquery_lazyload/tree/2.x).
