### ISSUE TITLE
可以延时加载，通过AJAX后加载的图片吗

### ISSUE THREAD

**Issue by senmeng** [tuupola/jquery_lazyload#321]
可以延时加载，通过AJAX后加载的图片吗

**Comment by df257** [comment]
我差点忍不住笑出来了-------->>>>>>>>哈哈哈
ps:这是外国人制作的插件。。。

**Comment by ghostuz** [comment]
It is really surprised to saw Chinese Question in github. but It is okay. there are many Chinese guys around here.
虽然在 github 中看到中文有点惊讶, 但是在这里天朝的牛人还是很多的

your question is not fit this jQuery plugins. this plugin is work for search images in the page DOM tree. then replace it to same loading image to avoid load every images in the html at the beginning. after page scroll to these images. lazy load it.
你提的问题好像和这个插件无关, 这个插件是通过遍历页面 DOM 节点找到图片, 用一张同样的加载图片替换, 避免在一开始加载全部页面的图片, 当页面滑动到原始图片的位置时, 再进行图片加载.

I guess you asked ajax load image. means load image by ajax returned image source. you can create a image dom element then attach onload event. append this image element to DOM tree after image success loaded.
我猜想你想问的 ajax 延时加载图片是指的使用 Ajax 返回的图片地址, 你可以创建一个图片元素, 附件 onload事件, 当图片成功加载后再挂载到页面 DOM树上.
