### ISSUE TITLE
Lazyloading for Backround Images not working with 1.9.7

### ISSUE THREAD

**Issue by OnlyPlanB** [tuupola/jquery_lazyload#322]
I like your script very much, but I have one small problem, I cant get it working with Background Images.
I have articles with Background Images and cant get them loaded like in your examples.
This is how my html looks like:

`<article class="lazy" style="background-image: url('http://anyimage.com/someimage.jpg')">                  </article>`

**Comment by vislogurov** [comment]
How  this bug fixed ?

**Comment by decadence** [comment]
How did you resolve it? AFAIK it doesn't support background-image.
