### ISSUE TITLE
Is it possible to use this plugin for lazyloading blockquotes from twitter?

### ISSUE THREAD

**Issue by OnlyPlanB** [tuupola/jquery_lazyload#327]
`<blockquote class="twitter-tweet" data-lang="de"><p lang="de" dir="ltr">Some text<a href="https://twitter.com/hashtag/some?src=hash">#hashtag</a> <a href="https://t.co/sample">pic.twitter.com/sample</a></p>&jdoe; John Doe <a href="https://twitter.com/j_doe/status/1234567890">21. july 2016</a></blockquote>`

**Comment by tuupola** [comment]
This plugin is for images only.
