### ISSUE TITLE
Feature: option to use background-color as placeholder (instead of an image)

### ISSUE THREAD

**Issue by rejhgadellaa** [tuupola/jquery_lazyload#333]
So we can make the placeholder a bit nicer just with some css or maybe js for random colors.

...or is this possible? Couldn't find it via google :)

**Comment by rejhgadellaa** [comment]
Hmm okay *maybe* this is a 'nevermind' thing. I just used 

`$(".lazy").lazyload({placeholder:"transparent.png"})`

and that does the trick because it then shows the css background-color :)

Still.. would be useful because this does take a (very little) extra data bandwidth (in my case a 24x24 png so not much but still) and setting it up. It would be cleaner to just use hex or rgb(a) colors

**Comment by RickOnline** [comment]
you can use this (transparent gif):

placeholder:"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="
