### ISSUE TITLE
How can I manually trigger the .lazyload?

### ISSUE THREAD

**Issue by ajsingh007** [tuupola/jquery_lazyload#346]
I have a webpage which filters list items. 

If a filter loads just a few items that fit onto a user's screen, images do not load. I notice that images only load on the scroll event. 

If i resize the window and scroll of course the images will load. But I'd rather trigger a manual load if a filter is pressed. How to do this?

**Comment by tuupola** [comment]
Trigger the event you have configured the plugin to use. It defaults to `scroll`.

```javascript
$("img.lazyload").triggetr("scroll");
```

**Comment by WindyRain0212** [comment]
Doesn't work.
for example
```javascript
$('.lazyload').lazyload({
    event: "loadImage"
});
```
will just load them on page load. Even without triggering the event.
Even happens on your example-webpage which is supposed to display them after 5 seconds of DOM-loading.

**Comment by tuupola** [comment]
Just tested and the images below the fold are loaded only after five seconds in the demo page.

http://www.appelsiini.net/projects/lazyload/enabled_timeout.html

**Comment by WindyRain0212** [comment]
Ahh so the images above the fold still get loaded? Alright, sorry then, should maybe include that detail in the description of the custom event though.

**Comment by ifocusrob** [comment]
This felt like a bug to me too, my application requires triggering all the images, not just the ones above the fold.

**Comment by tuupola** [comment]
For loading all images one could use 

```javascript
$("img.lazyload").trigger("appear");
```

**Comment by mkdizajn** [comment]
This worked for me >`lazyLoadInstance.update()`

**Comment by vahir2016** [comment]
> For loading all images one could use
> 
> ```js
> $("img.lazyload").trigger("appear");
> ```

Ty
