### ISSUE TITLE
Images loading slowly in chrome

### ISSUE THREAD

**Issue by PeteyRev** [tuupola/jquery_lazyload#347]
Hi, I love the plugin.

I am having an issue in chrome where the images are loading pretty slowly on chrome, the gray placeholder box is bigger than the image, and takes a few seconds after scrolling to it to appear. My images are around 1000 x 700px, does anyone know of a fix for this?

**Comment by Peteywiggin** [comment]
So the height issue is fixed, i accidentally had a rule for height auto on them that was overiding their set heights, but they are still loading very slowly.

**Comment by marenkov** [comment]
I have the same problem.
OS: Ubuntu 16.04
Chrome 55.0.2883.87 (64-bit)

**Comment by tuupola** [comment]
From timing console you should be able to see download timings. I do not see any possibilities how this plugin could affect download speed. My guess is either slow DNS responses or simply slow connection to the server hosting the images.
