### ISSUE TITLE
When user comes back to lazy-loaded page, images scramble and reload on scroll.

### ISSUE THREAD

**Issue by lennoxjw** [tuupola/jquery_lazyload#351]
When our users navigate away from the page using the plugin, and click "back" in their browser window, the page "re-lazy-loads" on scroll, but from the middle of the page, causing confusion.

**Comment by tuupola** [comment]
URL of a page where I could see this happening?

**Comment by NayFun** [comment]
You could trigger the scroll like that (example with jQuery) : 

`$( "#target" ).scroll();`

I had the same problem and i resolve it this way.

**Comment by tuupola** [comment]
No feedback, closing.
