### ISSUE TITLE
$('.selector').lazyload() doesn't check if the element was previously "enhanced"

### ISSUE THREAD

**Issue by jpolvora** [tuupola/jquery_lazyload#355]
Calling lazyload() multiple times causes the elements to be enhanced multiple times, causing the images to lazy load again.

I have an infinite scroll page that applies $('img.lazy') every time new content is loaded.

Currently I have to check manually if src is defined:

```
  $("img.lazy").each(function (index, el) {
                        if (!el.src) {
                            $(this).lazyload({
                                effect: "fadeIn"
                            });
                        }
                    });
```

**Comment by tuupola** [comment]
This should be fixed now.
