### ISSUE TITLE
several containers

### ISSUE THREAD

**Issue by baracuda2007** [tuupola/jquery_lazyload#357]
Hi.  Is it possible to use several containers? I have 3 different containers. Can you explain me?

**Comment by winternet-studio** [comment]
I had the same question but figured out this work-around:

	$('.your-containers').each(function() {
		$(this).find('img.lazy').lazyload({
			container: $(this)
		});
	});

**Comment by tuupola** [comment]
Something like this should work too:

```JavaScript 
$(function() {
      $("#container img.lazy").lazyload({container: $("#container")});
      $("#container2 img.lazy").lazyload({container: $("#container2")});
      $("#container3 img.lazy").lazyload({container: $("#container3")});
  });
```
