### ISSUE TITLE
Lazy loading 'stuck' on big page with both horizontal and vertical scrolling

### ISSUE THREAD

**Issue by nickdekruijk** [tuupola/jquery_lazyload#362]
See http://gijsbakker.nognietklaar.com/work for example
In my case it loads fine when scrolling down until I reach the year 2000
When scrolling the items in 2001 horizontally the last couple of items aren't loaded either. For some reason the lazyload plugin stops working until I scroll further and back up again. 
Any ideas?

**Comment by der-krueger** [comment]
I have the same issue. Did you find any solution?

**Comment by nickdekruijk** [comment]
Ended up using https://github.com/verlok/lazyload instead
