### ISSUE TITLE
Why all images is preloaded before scroll?

### ISSUE THREAD

**Issue by AxelBriche** [tuupola/jquery_lazyload#365]
I dont scroll and all images is preloaded and result in many useless http request:
https://puu.sh/tCt7u/8b5c1a4d38.png

It is possible to do the http request only when the user scroll and the image need to appear on the screen? Thanks.

**Comment by tuupola** [comment]
You seem to be using [data:uri](https://en.wikipedia.org/wiki/Data_URI_scheme) images? Thus no http requests are made since your images are inline.
