### ISSUE TITLE
 Images loading before scroll

### ISSUE THREAD

**Issue by shubham1208** [tuupola/jquery_lazyload#366]
I am lazy loading the images but they all preload even before coming in the viewport.
check here: http://www.shelfjoy.com

**Comment by tuupola** [comment]
You must have the placeholder image in the `style="background-image: url('..')"`. See the [example]( http://www.appelsiini.net/projects/lazyload/enabled_background.html).

**Comment by shubham1208** [comment]
Working now, thanks.
