### ISSUE TITLE
The img labels are dynamic appended to the DOM by underscore.js,lazyload has not effect. 

### ISSUE THREAD

**Issue by yang06061079** [tuupola/jquery_lazyload#369]
The underscore.js template is:
![image](https://cloud.githubusercontent.com/assets/18298611/22880555/92fa6a88-f21d-11e6-89d2-17d33bc772f3.png)

The img labels in the DOM are normal.
Why is it working?
Hope for you reply!
Thank you!

**Comment by jkrehm** [comment]
I imagine you're well past caring about this, but just in case you are not or someone else comes upon this, I'd bet the reason it's not working is that lazyload hasn't been bound to the image. When you use the template to insert into the DOM, you'll need to bind lazyload to the newly inserted image elements.

For example:
```
(function() {
  var listTmpl = _.template(
    $('.project-list-tmpl').html()
  );
  $('#container')
    .append(listTmpl({ ... })
    .find('img').lazyload({ ... });
})();
```

**Comment by tuupola** [comment]
What @jkrehm said.
