### ISSUE TITLE
Imges outside of viewport would be loaded before user scrolls to them

### ISSUE THREAD

**Issue by zhaoxueyin000** [tuupola/jquery_lazyload#371]
Before I scroll to the images,they are loaded.What can I do to prevent

**Comment by tuupola** [comment]
URL of the page which has the problem?

**Comment by zhaoxueyin000** [comment]
https://pay.sina.com.cn/zjtg

**Comment by zhaoxueyin000** [comment]
https://pay.sina.com.cn/zjtg
for the last page

**Comment by tuupola** [comment]
In your JavaScript code you bind lazy load to images with class lazy which are inside `.section8`. 

```a("img.lazy").lazyload({effect:"fadeIn",container:a(".section8")})```

In your html code there however is no such images.

**Comment by zhaoxueyin000** [comment]
![image](https://cloud.githubusercontent.com/assets/17424860/23254052/aaf34c82-f9f1-11e6-9f33-5125f85c10fa.png)
I used template to input images.This is original code

**Comment by winternet-studio** [comment]
@zhaoxueyin000 FYI your width and height values should not include "px"
