### ISSUE TITLE
Turn off waiting for load for big animated GIF files?

### ISSUE THREAD

**Issue by jitbit** [tuupola/jquery_lazyload#375]
Is there any way I can `.show()` the image without waiting until it's loaded?

This can be an issue with big animated GIF file that can be 3-4 megabyte, **but I want them to start playing animation right away**

**Comment by tuupola** [comment]
This is not currently possible. You might want to check [2.x](https://github.com/tuupola/jquery_lazyload/tree/2.x) though to see if it fixes your problem.
