### ISSUE TITLE
Will this work on images in a hidden DIV?

### ISSUE THREAD

**Issue by MacMajor01** [tuupola/jquery_lazyload#378]
[edit: My apologies, this is not an issue, but a Question.]

Hi and thanks in advance!

Before I delve into this, please let me know if this will actually work?

I have a page that contains 191 images. Assigned to those are 191 checkboxes, and each image is in a hidden div (along with static text, and text associated to further hidden text). The image and static text is shown when the user clicks on the assigned checkbox.

Will Lazy Load work with this setup; with the images being hidden in a div???

Tracy

**Comment by MacMajor01** [comment]
Found my answer once  I dove into it:  "skip_invisible : true" after initializing the plugin:

$("img.lazy").lazyload({
    skip_invisible : true
});

**Comment by MacMajor01** [comment]
I think I got my answer... no go. Is there a way around this problem? Here's what happens. I have page with a gazillion checkboxes w/names next to em. If the page is idle (no use of window scrollbar), and the user is selecting different checkboxes, the image will not load along with the hidden content... not unless of course, you move the scrollbar.... but a user is not going to know to do that to get the image to load!

Can you use the "event : click" "in_addition_to". Ex. the user is clicking different checkboxes to display hidden content, but only seeing the grey image... w/out them scrolling to reveal the image, can clicking to "another" option... and not set as "the only option" to display the image?

Hope this makes sense???

Suggestions Please!???

**Comment by reportingforduty** [comment]
@MacMajor01 Exactly what I was looking for.

https://github.com/verlok/lazyload/issues/99

**Comment by tuupola** [comment]
When use clicks the checkbox you can trigger `scroll` event with JavaScript. `$(window).trigger("scroll")`.
