### ISSUE TITLE
If my picture set the display: none, it will be the default load?

### ISSUE THREAD

**Issue by buynao** [tuupola/jquery_lazyload#382]
hi, for the 1.x version, I have a question:
In the 1.x source, I see skip_invisible set to false.
`        var settings = {
            skip_invisible  : false,
        };`
Then traverse the elements, through this condition to judge, the image lazy load.
` if (settings.skip_invisible && !$this.is(":visible")) {
        return;
 }`
In this case, the default loading display: none picture elements, why should this set up? What is the meaning of this conditional judgment?

If you have time, please tell me why, thank you very much.

**Comment by tuupola** [comment]
In the old times when browsers were much slower one could set `skip_invisible : true` and images which were hidden with CSS would be ignored by the plugin. This way there would be smaller amount if images to check and plugin worked faster.
