### ISSUE TITLE
Why isn't my simple code working?

### ISSUE THREAD

**Issue by prateekvarma** [tuupola/jquery_lazyload#387]
Below is a very basic example, and images load before i scroll onto them. What possibly am i doing wrong?

```
<!DOCTYPE html>
<html>
<head>
	<title>Lazy loading</title>
	                
</head>
<body>

<img class="lazyload" data-src="img1.jpg">

<img class="lazyload" data-src="img2.jpg">

<img class="lazyload" data-src="img3.jpg">

<img class="lazyload" data-src="img4.jpg">

<img class="lazyload" data-src="img5.jpg">

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/lazyload@2.0.0-beta.1/lazyload.js"></script>
<script>
	lazyload();
</script>
</body>
</html>
```

**Comment by hworm4** [comment]
this is the right syntax 
replace your <script> whith this code
<script>
 $("img.lazyload").lazyload({
    effect : "fadeIn"
  });
</script>

**Comment by Globulopolis** [comment]
Because new version in WIP status and not working at this time.

**Comment by prateekvarma** [comment]
@hworm4 is that jquery? If yes, then  why not vanilla JS?

**Comment by hworm4** [comment]
because it called (jquery_lazyload)?

**Comment by prateekvarma** [comment]
@hworm4 hmm, you're right. Although this version is supposed to work also with vanilla JS as the docs say. It's late night here in my country, i will check this tomorrow and leave a comment. Many thanks!

**Comment by tuupola** [comment]
@prateekvarma because your images do not have sizes set so they all are 1x1 or 0x0 size which means they all are in viewport when the html loads. Set dimensions either via css or img tag.

@hworm4 2.x is vanilla javascript. The is no need for jQuery. The repository name just has not been changed yet.

**Comment by prateekvarma** [comment]
@tuupola  Thank you for clarifying.
After adding size to images, for some reason it still does not lazyload for me :(

`<img class="lazyload" height="268px" width="416px" data-src="img3.png">`

Is there something else i'm missing?

**Comment by ghost** [comment]
@tuupola So there's a 2.x version using only native JS, Great news Thanx for your hard work.

@prateekvarma Sorry, it seems my info are out dated.

**Comment by bhansa** [comment]
@prateekvarma  can you create a small example at [jsfiddle.net](https://jsfiddle.net)

**Comment by prateekvarma** [comment]
@bhansa Sorry for the late reply.
It works now! I'm not sure what was i missing. here's the fiddle - https://jsfiddle.net/prtkvarma/2tm3q7ha/
