### ISSUE TITLE
intersectionRatio and reloading

### ISSUE THREAD

**Issue by sovanyio** [tuupola/jquery_lazyload#390]
Inside the IntersectionObserver, the comparison for intersectionRatio > 0 causes images to not load when reloading a page that is partially scrolled and the images are partially displayed.
The mozilla demo does an either/or comparison https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API so it always runs on collisions. I think that the comparison should be removed, or at least exposed via an option.

Observer:
```
                   if (entry.intersectionRatio > 0) {
                        self.observer.unobserve(entry.target);
                        let src = entry.target.getAttribute(self.settings.src);
                        let srcset = entry.target.getAttribute(self.settings.srcset);
                        if ('img' === entry.target.tagName.toLowerCase()) {
                            if (src) {
                                entry.target.src = src;
                            }
                            if (srcset) {
                                entry.target.srcset = srcset;
                            }
                        } else {
                            entry.target.style.backgroundImage = 'url(" + src + ")';
                        }
                     }
```

**Comment by sovanyio** [comment]
Actually, think the conditional is `.isIntersecting`

**Comment by tuupola** [comment]
Can you give an example url where this is happening. Also which browser? I just tested with [this page](https://appelsiini.net/2017/trilateration-with-n-points/) and I cannot reproduce. I do agree that using `.isIntersecting` property is much cleaner though.

**Comment by sovanyio** [comment]
Hm I noticed this when testing locally. I tried to write a codepen, but the scroll position of the pen isn't retained when refreshing.

But what I am seeing on the example you linked to is that the images are not lazyloaded on Safari or IE, they all load 'normally'.
That behavior can also be see on the pen https://codepen.io/sovanyio/pen/BwQreM

**Comment by pix666** [comment]
I've found that if you scroll page by one pixel, you can catch a moment when image became visible, but `.intersectionRatio` is `0` (Chromium browser). So, image is not loaded.
You should use `.isIntersecting`

**Comment by pix666** [comment]
Look at this.
`isIntersecting` is `True`, but `intersectionRatio` is `0`

![screenshot](https://user-images.githubusercontent.com/6928240/39663225-7ae61e84-5080-11e8-98d7-44b087fd6b3b.png)
