### ISSUE TITLE
Setting for rootMargin

### ISSUE THREAD

**Issue by shumoapp** [tuupola/jquery_lazyload#402]
Hello, 

It would be nice to allow us to configure the rootMargin Intersection Observer setting. This way we can accomplish pre-loading of images that are not yet in the viewport. The end result would be the users will never see an empty/loading image while they scroll at normal speed to the bottom of the page.

**Comment by andomain** [comment]
Hi

I recently needed this for a project so extended the default options and allowed these to be overridden with a config argument, e.g. `lazyload(lazyImages, {"rootMargin": "150px"});`

All 3 arguments to the IntersectionObserver can be specified or they will just use default values

I'd be happy to submit a PR for this?

**Comment by tuupola** [comment]
Fixed via #416.
