### ISSUE TITLE
Ie 11 Image loading Issues outside the viewport

### ISSUE THREAD

**Issue by ksz2013** [tuupola/jquery_lazyload#403]
Hi @tuupola ,

I am using currently the v1 version of your plugin and on internet explorer images that  are not in the viewport after page scroll they are not loaded, just the placeholder image is displayed. (Initial images in the viewport are properly loaded.)
Issue encountered just on the internet explorer, on other browsers everything works properly.

If a resize the browser they start to appear.

Have someone else encountered this problem, or do you have some kind of workaround for this?
I can send you demo page as well, where the problem appears.

Thanks.

**Comment by tuupola** [comment]
This has been fixed via #417.
