### ISSUE TITLE
threshold 

### ISSUE THREAD

**Issue by bisfoaldo** [tuupola/jquery_lazyload#406]
Hello, How to set threshold in this new beta version?

**Comment by tennox** [comment]
I guess this feature is not implemented yet.

You could use:
https://github.com/verlok/lazyload

**Comment by tom10271** [comment]
It is unbelievable that this repo got over 7K stars without implementing this basic function

**Comment by tuupola** [comment]
Unbelieveable pull requests are welcome.

**Comment by bisfoaldo** [comment]
Unfortunately I will have to move to another lazyload script... this feature is a must running photo only dedicated sites

**Comment by butch2k** [comment]
You need to set rootmargin for this to work.
By default it's set to 0px, if you set it to 200px, you extend the hitbox 200px each side, hence the observer detects an intersect 200px outside of the original box, it's the way to implement a threshold with an intersect observer.

https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/rootMargin

**Comment by tuupola** [comment]
Yeah, it should actually be exposed as a config option so `rootmargin` would act as the `threshold` in old version

**Comment by butch2k** [comment]
Definitely ! It was the first thing I looked into when moving to 2.0.

**Comment by bisfoaldo** [comment]
Thank you @butch2k! this have fixed my issue
