### ISSUE TITLE
firefox 47.0.2 breaks with this.images.forEach is not a function

### ISSUE THREAD

**Issue by migliori** [tuupola/jquery_lazyload#413]
The nodeList loop L.135 in lazyload.js throws a console error.

The solution is to replace:
`this.images.forEach(function(image) {`

with:
`Array.prototype.forEach.call(this.images, function(image) {`

**Comment by luigifab** [comment]
Same error with my beautiful Firefox 45.

**Comment by tuupola** [comment]
This has been fixed via #417.
