### ISSUE TITLE
[bug] image src  contains () can't load

### ISSUE THREAD

**Issue by zwpro** [tuupola/jquery_lazyload#427]
If the data-src contains () , then backgroundImage cannot set url(src)

In your source code：
`entry.target.style.backgroundImage = "url(" + src + ")";`
if the data-src=“https://t1.27270.com/uploads/tu/201809/559/1%20(2).jpg”  ，then the () Ambiguity

I tested it, 
`"url('" + src + "')"`
this is okay

**Comment by tuupola** [comment]
This was fixed with #428.
