### ISSUE TITLE
Any scope for retina @x2 swap out?

### ISSUE THREAD

**Issue by andrewminton** [tuupola/jquery_lazyload#63]
https://github.com/neoziro/lazy-retina

Was looking at this lazyload implementation and wondering if some sort of retina detection would be useful for this script as well?

Would be ace to have the Retina support in one lazyload library rather than attempting to merge 2 in html source. 

Thoughts?

**Comment by mestr3** [comment]
Any chance of some retina solution be merged? I saw no mention in the documentation about using retina images with the current plugin.

**Comment by verlok** [comment]
Check out this https://github.com/verlok/lazyload 
It's a lazy load script much faster than jQuery LazyLoad, to which you can migrate easily, and which support the srcset attribute so retina images are fully supported. 
We use it in production in the category pages of many of our ecommerce websites. 
Let me know!

--
Andrea Verlicchi
www.andreaverlicchi.eu

**Comment by tuupola** [comment]
With [2.x](https://github.com/tuupola/jquery_lazyload/tree/2.x) you can support retia displays with something like:

```html
<img class="lazyload"
     src="thumbnail.jpg"
     data-src="normal.jpg"
     data-srcset="normal.jpg 1x, retina.jpg 2x"
     width="1024" height="768" />
```
