### ISSUE TITLE
Binding multiple events

### ISSUE THREAD

**Issue by eugenemiretsky** [tuupola/jquery_lazyload#65]
Hi,
Is it possible to bind multiple events? 
Some scenarios where it could be useful:
1) Autocomplete like search box   I want to be able to add filter all the images and load them. Now, as a work around I need to trigger the scrol event. 
2) Pre-load the hidden images. I have a list of 200+ images, only the first 5 are visible. So I want to first load only the first 5, but after a few sec the browser is ideal, so I might as well load the other images. It would be nice if I could bind the sporty event.

**Comment by timersys** [comment]
+1 for this I got same problem

**Comment by tuupola** [comment]
Maybe #72 helps?
