### ISSUE TITLE
Exprose error handler

### ISSUE THREAD

**Issue by daraser** [tuupola/jquery_lazyload#68]
Right now when loading an image the error won't be triggered if image would give a 404 so let's trigger the error event  which is set to the original image. 

This is the my code for exposing loading error:

<pre>
$("&lt;img /&gt;")
.bind("load", function() {
    $(self)
        .hide()
        .attr("src", $(self).data("original"))
        [settings.effect](settings.effectspeed);
    self.loaded = true;
})
.bind("error", function(){
    // Lazy loader hides the 404 error, so to be able to add callback code
    $(self).trigger('error');
})
.attr("src", $(self).data("original"));
</pre>

Thanks.

**Comment by pwninstein** [comment]
:+1: on this Can confirm that @daraser's solution (and @EricTousignant's minified fix) works. Depending on what version of the plugin you have, the variable names may be different, so http://jsbeautifier.org/ helped me to find the right place and name.

**Comment by tuupola** [comment]
You are not supposed to edit minified versions of JavaScript. They are automatically generate by tools such as jsmin.

**Comment by daraser** [comment]
@tuupola will you merge my fix if I setup a pull request?
